### ISSUE TITLE
Negotiate::fallBack() Too few arguments to function

### ISSUE THREAD

**Issue by knuz92** [simplesamlphp/simplesamlphp-module-negotiate#8]
Hi, 

when the Module Negotiate trys to fallback because ist gets no Kerberos Ticket it fails with this error:

`SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 src/SimpleSAML/Error/ExceptionHandler.php:35 (SimpleSAML\Error\ExceptionHandler::customExceptionHandler)
1 vendor/symfony/error-handler/ErrorHandler.php:531 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: ArgumentCountError: Too few arguments to function SimpleSAML\Module\negotiate\Auth\Source\Negotiate::fallBack(), 0 passed in /var/simplesamlphp2/vendor/symfony/http-kernel/HttpKernel.php on line 101 and exactly 1 expected
Backtrace:
5 modules/negotiate/src/Auth/Source/Negotiate.php:286 (SimpleSAML\Module\negotiate\Auth\Source\Negotiate::fallBack)
4 vendor/symfony/http-kernel/HttpKernel.php:101 (Symfony\Component\HttpKernel\HttpKernel::Symfony\Component\HttpKernel\{closure})
3 [builtin] (call_user_func_array)
2 modules/negotiate/src/Controller/NegotiateController.php:280 (Symfony\Component\HttpFoundation\StreamedResponse@anonymousmodules/negotiate/src/Controller/NegotiateController.php:267$96::sendContent)
1 vendor/symfony/http-foundation/Response.php:425 (Symfony\Component\HttpFoundation\Response::send)
0 public/module.php:24 (N/A)`

Versions installed:
symfony v6.4
simplesamlphp v 2.1.1
simplesamlphp-module-negotiate  v2.1.1

**Comment by tvdijen** [comment]
Try downgrading Symfony to 6.2 ... There appears to be a breaking change in 6.3+

**Comment by tvdijen** [comment]
v2.1.2 was released to address this issue.
